// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type SuccessErrorReturn = {
    success: boolean;
    error: string | null;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetCurrentDirFsGetCwdGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/fs/get_cwd';
};

export type GetCurrentDirFsGetCwdGetResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type GetCurrentDirFsGetCwdGetResponse = GetCurrentDirFsGetCwdGetResponses[keyof GetCurrentDirFsGetCwdGetResponses];

export type ListDirFsListDirGetData = {
    body?: never;
    path?: never;
    query?: {
        path?: string | null;
    };
    url: '/fs/list_dir';
};

export type ListDirFsListDirGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDirFsListDirGetError = ListDirFsListDirGetErrors[keyof ListDirFsListDirGetErrors];

export type ListDirFsListDirGetResponses = {
    /**
     * Successful Response
     */
    200: Array<{
        [key: string]: string;
    }>;
};

export type ListDirFsListDirGetResponse = ListDirFsListDirGetResponses[keyof ListDirFsListDirGetResponses];

export type ChangeDirFsChangeDirNewdirPutData = {
    body?: never;
    path: {
        newdir: string;
    };
    query?: never;
    url: '/fs/change_dir/{newdir}';
};

export type ChangeDirFsChangeDirNewdirPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChangeDirFsChangeDirNewdirPutError = ChangeDirFsChangeDirNewdirPutErrors[keyof ChangeDirFsChangeDirNewdirPutErrors];

export type ChangeDirFsChangeDirNewdirPutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ChooseVcfChooseVcfVcfPathPutData = {
    body?: never;
    path: {
        vcf_path: string;
    };
    query: {
        tmp: string;
    };
    url: '/choose_vcf/{vcf_path}';
};

export type ChooseVcfChooseVcfVcfPathPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChooseVcfChooseVcfVcfPathPutError = ChooseVcfChooseVcfVcfPathPutErrors[keyof ChooseVcfChooseVcfVcfPathPutErrors];

export type ChooseVcfChooseVcfVcfPathPutResponses = {
    /**
     * Successful Response
     */
    200: SuccessErrorReturn;
};

export type ChooseVcfChooseVcfVcfPathPutResponse = ChooseVcfChooseVcfVcfPathPutResponses[keyof ChooseVcfChooseVcfVcfPathPutResponses];

export type ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutData = {
    body?: never;
    path: {
        annotation_path: string;
    };
    query: {
        tmp: string;
    };
    url: '/choose_annotation_file/{annotation_path}';
};

export type ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutError = ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutErrors[keyof ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutErrors];

export type ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutResponses = {
    /**
     * Successful Response
     */
    200: SuccessErrorReturn;
};

export type ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutResponse = ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutResponses[keyof ChooseAnnotationFileChooseAnnotationFileAnnotationPathPutResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};